### Create new book
POST http://localhost:8000/api/books
Content-Type: application/json

{
  "judul": "Clean Code 101",
  "penulis": "Robert C. Martin",
  "penerbit": "Prentice Hall",
  "tahunTerbit": 2008,
  "isbn": "978-0132350988",
  "stok": 10,
  "kategori": "Programming"
}

### GET list of books
GET http://localhost:8000/api/books
    ?judul=
    &kategori=
    &page=1
    &limit=2

### GET detail of book by ID
GET http://localhost:8000/api/books/f83bf9dc-c316-4755-9a1c-d0a8e979cfa1

### UPDATE book by ID
PUT http://localhost:8000/api/books/f83bf9dc-c316-4755-9a1c-d0a8e979cfa1
Content-Type: application/json

{
  "judul": "Clean Code",
  "penulis": "Robert C. Martin",
  "penerbit": "Prentice Hall",
  "tahunTerbit": 2008,
  "isbn": "978-0132350999",
  "stok": 10,
  "kategori": "Programming 001"
}

### DELETE book by ID
DELETE http://localhost:8000/api/books/f83bf9dc-c316-4755-9a1c-d0a8e979cfa1

### Borrow book by ID
POST http://localhost:8000/api/books/f83bf9dc-c316-4755-9a1c-d0a8e979cfa1/borrow
Content-Type: application/json

{
  "qty": 1
}